require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CardapiosController do

  # This should return the minimal set of attributes required to create a valid
  # Cardapio. As you add validations to Cardapio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CardapiosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cardapios as @cardapios" do
      cardapio = Cardapio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cardapios).should eq([cardapio])
    end
  end

  describe "GET show" do
    it "assigns the requested cardapio as @cardapio" do
      cardapio = Cardapio.create! valid_attributes
      get :show, {:id => cardapio.to_param}, valid_session
      assigns(:cardapio).should eq(cardapio)
    end
  end

  describe "GET new" do
    it "assigns a new cardapio as @cardapio" do
      get :new, {}, valid_session
      assigns(:cardapio).should be_a_new(Cardapio)
    end
  end

  describe "GET edit" do
    it "assigns the requested cardapio as @cardapio" do
      cardapio = Cardapio.create! valid_attributes
      get :edit, {:id => cardapio.to_param}, valid_session
      assigns(:cardapio).should eq(cardapio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cardapio" do
        expect {
          post :create, {:cardapio => valid_attributes}, valid_session
        }.to change(Cardapio, :count).by(1)
      end

      it "assigns a newly created cardapio as @cardapio" do
        post :create, {:cardapio => valid_attributes}, valid_session
        assigns(:cardapio).should be_a(Cardapio)
        assigns(:cardapio).should be_persisted
      end

      it "redirects to the created cardapio" do
        post :create, {:cardapio => valid_attributes}, valid_session
        response.should redirect_to(Cardapio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cardapio as @cardapio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cardapio.any_instance.stub(:save).and_return(false)
        post :create, {:cardapio => { "nome" => "invalid value" }}, valid_session
        assigns(:cardapio).should be_a_new(Cardapio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cardapio.any_instance.stub(:save).and_return(false)
        post :create, {:cardapio => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cardapio" do
        cardapio = Cardapio.create! valid_attributes
        # Assuming there are no other cardapios in the database, this
        # specifies that the Cardapio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cardapio.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => cardapio.to_param, :cardapio => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested cardapio as @cardapio" do
        cardapio = Cardapio.create! valid_attributes
        put :update, {:id => cardapio.to_param, :cardapio => valid_attributes}, valid_session
        assigns(:cardapio).should eq(cardapio)
      end

      it "redirects to the cardapio" do
        cardapio = Cardapio.create! valid_attributes
        put :update, {:id => cardapio.to_param, :cardapio => valid_attributes}, valid_session
        response.should redirect_to(cardapio)
      end
    end

    describe "with invalid params" do
      it "assigns the cardapio as @cardapio" do
        cardapio = Cardapio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cardapio.any_instance.stub(:save).and_return(false)
        put :update, {:id => cardapio.to_param, :cardapio => { "nome" => "invalid value" }}, valid_session
        assigns(:cardapio).should eq(cardapio)
      end

      it "re-renders the 'edit' template" do
        cardapio = Cardapio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cardapio.any_instance.stub(:save).and_return(false)
        put :update, {:id => cardapio.to_param, :cardapio => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cardapio" do
      cardapio = Cardapio.create! valid_attributes
      expect {
        delete :destroy, {:id => cardapio.to_param}, valid_session
      }.to change(Cardapio, :count).by(-1)
    end

    it "redirects to the cardapios list" do
      cardapio = Cardapio.create! valid_attributes
      delete :destroy, {:id => cardapio.to_param}, valid_session
      response.should redirect_to(cardapios_url)
    end
  end

end
